# Generated by Django 5.2.1 on 2025-10-28 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ejerciciosguardados'),
    ]

    operations = [
        migrations.CreateModel(
            name='RutinasGuardados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_guardado', models.DateTimeField(auto_now_add=True)),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.rutina')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.usuario')),
            ],
            options={
                'db_table': 'rutina_guardados',
            },
        ),
        migrations.DeleteModel(
            name='EjerciciosGuardados',
        ),
    ]
