# Generated by Django 5.2.1 on 2025-10-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rutinasguardados_delete_ejerciciosguardados'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_vinculacion',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
