# Generated by Django 5.2.1 on 2025-11-09 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_usuario_codigo_vinculacion_usuario_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasena',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
