# Generated by Django 5.2.1 on 2025-11-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usuario_contrasena'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, default=36.6, max_digits=5),
            preserve_default=False,
        ),
    ]
