# Generated by Django 5.2.6 on 2025-11-18 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_usuario_contrasena'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animacion',
            name='url_anima',
        ),
        migrations.AddField(
            model_name='animacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='animaciones/'),
        ),
    ]
