# Generated by Django 5.2.1 on 2025-11-19 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_lectura_temperatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='rutina',
            name='usuario',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='api.usuario'),
            preserve_default=False,
        ),
    ]
