# Generated by Django 5.2.1 on 2025-11-20 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rutina_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.TextField()),
            ],
            options={
                'db_table': 'imagenes',
            },
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='animacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.imagen'),
        ),
        migrations.DeleteModel(
            name='Animacion',
        ),
    ]
