# Generated by Django 5.2.1 on 2025-11-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_imagen_alter_ejercicio_animacion_delete_animacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen_perfil',
            field=models.TextField(blank=True, null=True),
        ),
    ]
