# Generated by Django 5.2.1 on 2025-11-20 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_usuario_imagen_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='url',
            field=models.ImageField(upload_to='ejercicios/'),
        ),
    ]
